{% set name = "napari-cellseg3d" %}
{% set version = "0.2.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2937a2d20d1bcc9f131ffb532935928c2125671fcb9f12ba890bebdd8860bb16

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >=8
    - wheel

  run:
    - python >={{ python_min }}
    - imagecodecs >=2023.3.16
    - itk
    - matplotlib-base >=3.4.1
    - monai >=0.9
    - einops
    - nibabel
    - napari >=0.4.14
    - numpy
    - pyclesperanto
    - pytorch >=1.11
    - qtpy
    - scikit-image >=0.19.2
    - tifffile
    - toml
    - tqdm

test:
  imports:
    - napari_cellseg3d

  commands:
    - python -m npe2 validate napari-cellseg3d

  requires:
    - python {{ python_min }}
    - npe2

about:
  home: https://github.com/AdaptiveMotorControlLab/CellSeg3D
  summary: Plugin for cell segmentation in 3D
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - C-Achard
    - jaimergp
