{% set name = "napari-cellseg3d" %}
{% set version = "0.0.2rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6e39608d406b617596a6879444f9bcebcbdcae96a25dd111229a387e4a8dc994

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dask-image >=0.6.0
    - einops
    - imageio-ffmpeg >=0.4.5
    - itk >=5.2.0
    - magicgui
    - matplotlib-base >=3.4.1
    - monai >=0.9.0
    - napari >=0.4.14
    - nibabel
    - numpy
    - opencv >=4.5.5
    - pillow
    - pims
    - python >=3.8
    - pytorch >=1.11
    - qtpy
    - scikit-image >=0.19.2
    - tifffile >=2022.2.9
    - tqdm
    - vispy >=0.9.6

test:
  imports:
    - napari_cellseg3d
    - napari_cellseg3d.models
    - napari_cellseg3d.res
    - napari_cellseg3d.conftest
    - napari_cellseg3d.drafts
    - napari_cellseg3d.interface
    - napari_cellseg3d.launch_review
    - napari_cellseg3d.log_utility
    - napari_cellseg3d.model_framework
    - napari_cellseg3d.model_instance_seg
    - napari_cellseg3d.model_workers
    - napari_cellseg3d.plugin_base
    - napari_cellseg3d.plugin_convert
    - napari_cellseg3d.plugin_crop
    - napari_cellseg3d.plugin_dock
    - napari_cellseg3d.plugin_helper
    - napari_cellseg3d.plugin_metrics
    - napari_cellseg3d.plugin_model_inference
    - napari_cellseg3d.plugin_model_training
    - napari_cellseg3d.plugin_review
    - napari_cellseg3d.plugin_utilities
    - napari_cellseg3d.plugins
    - napari_cellseg3d.utils
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AdaptiveMotorControlLab/CellSeg3d
  summary: plugin for cell segmentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - C-Achard
    - goanpeca
    - jaimergp
