{% set name = "napari-cellseg3d" %}
{% set version = "0.0.2rc6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 10cec21568268cdc488a519de72c9222b6c3b2087425b4ea4770a5779cc7336c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dask-image >=0.6.0
    - einops
    - imageio-ffmpeg >=0.4.5
    - itk >=5.2.0
    - magicgui
    - matplotlib-base >=3.4.1
    - monai >=0.9.0
    - napari >=0.4.14
    - nibabel
    - numpy
    - opencv >=4.5.5
    - pillow
    - pims
    - python >=3.8
    - pytorch >=1.11
    - qtpy
    - scikit-image >=0.19.2
    - tifffile >=2022.2.9
    - tqdm
    - vispy >=0.9.6

test:
  imports:
    - napari_cellseg3d
    - napari_cellseg3d.res
    - napari_cellseg3d.plugins
    - napari_cellseg3d.utils
    - napari_cellseg3d.interface
    - napari_cellseg3d.code_plugins.plugin_base
    - napari_cellseg3d.code_plugins.plugin_convert
    - napari_cellseg3d.code_plugins.plugin_crop
    - napari_cellseg3d.code_plugins.plugin_helper
    - napari_cellseg3d.code_plugins.plugin_metrics
    - napari_cellseg3d.code_plugins.plugin_model_inference
    - napari_cellseg3d.code_plugins.plugin_model_training
    - napari_cellseg3d.code_plugins.plugin_review
    - napari_cellseg3d.code_plugins.plugin_review_dock
    - napari_cellseg3d.code_plugins.plugin_utilities
    - napari_cellseg3d.code_models.models
    - napari_cellseg3d.code_models.model_framework
    - napari_cellseg3d.code_models.model_instance_seg
    - napari_cellseg3d.code_models.model_workers
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AdaptiveMotorControlLab/CellSeg3d
  summary: plugin for cell segmentation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - C-Achard
    - goanpeca
    - jaimergp
